In [1]:
import boto3
import pandas as pd
import os
from io import BytesIO
import json

In [2]:
with open('DSSC-FC-MVP-Configuration.json', 'r') as openfile:
    json_object = json.load(openfile)

In [6]:
# json_object

In [2]:
# Client connection authentication with AWS S3
client = boto3.client('s3',
                      aws_access_key_id=json_object['aws_access_key_id'],
                      aws_secret_access_key=json_object['aws_secret_access_key'])

In [4]:
# Find all the csv file in the current directory and get the file and store it to bucket one by one
for file in os.listdir():
    if '.csv' in file:
        upload_file_bucket = 'dssc-fc-mvp'
        upload_file_key = 'data-collection/' + str(file)
        client.upload_file(file,
                           upload_file_bucket,
                           upload_file_key)

In [10]:
# Created the function which connects the code with AWS S3 and 
# take the input as company name and gives us the data of that comapny 
# which we have already stored in S3 bucket
def get_file(company_name):
    client = boto3.client('s3',
                          aws_access_key_id=json_object['aws_access_key_id'],
                          aws_secret_access_key=json_object['aws_secret_access_key'])
    file = client.get_object(Bucket='dssc-fc-mvp',
                             Key='data-collection/'+ company_name +'_data.csv')
    read_file = file['Body'].read()
    read_file_csv = pd.read_csv(BytesIO(read_file))
    
    return read_file_csv

Alphabet Data: Alphabet,
Apple Data: Apple,
IBM Data: IBM,
Microsoft Data: Microsoft,
Meta Data: Meta,
Royal Bank of Canada Data: RBC,
Bank of Nova Scotia Data: Scotia,
Bank of Montreal Data: BMO,
Taiwan Semiconductor Manufacturing Data: TSM,
Nvidia Data: Nvidia,
Texas Instruments Data: TXN,
Oracle Data: Oracle,
Cisco Data: Cisco,
Verizon Communications Data: VZ

In [11]:
Data = get_file('Apple')

In [12]:
Data

,Unnamed: 0,Open,High,Low,Close,Adj Close,Volume
0,2021-01-04 09:30:00-05:00,133.520004,133.611603,130.380005,131.053604,131.053604,27653145
1,2021-01-04 10:30:00-05:00,131.054993,131.309998,129.399994,129.895004,129.895004,20134055
2,2021-01-04 11:30:00-05:00,129.889893,130.089996,126.760002,128.250000,128.250000,23694210
3,2021-01-04 12:30:00-05:00,128.246902,129.110001,127.630096,129.039795,129.039795,14745063
4,2021-01-04 13:30:00-05:00,129.039993,129.199997,128.595001,128.960007,128.960007,10861778
...,...,...,...,...,...,...,...
3128,2022-10-12 11:30:00-04:00,139.699997,140.139999,139.110001,139.160004,139.160004,7067938
3129,2022-10-12 12:30:00-04:00,139.151794,139.600006,138.940002,139.164001,139.164001,5265879
3130,2022-10-12 13:30:00-04:00,139.125000,139.330002,138.250000,139.220001,139.220001,9917788
3131,2022-10-12 14:30:00-04:00,139.220001,139.360001,138.160004,138.479996,138.479996,7332972
3132,2022-10-12 15:30:00-04:00,138.511093,138.800003,138.259995,138.300003,138.300003,6377537